version: 2.1
jobs:

  build:

    docker:

      - image: circleci/node:10.15-stretch-browsers

    working_directory: ~/project/

    steps:

      - checkout

      - run:

          name: 'Install dependencies'

          command: npm install

      - run:

          name: 'Push to UXPin'

          command: npm run push
